import './globals.css';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import ReduxProviders from '@/redux/providers';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
    return (
        <html lang="en">
            <body
                className={`${inter.className} bg-gradient-to-b from-sky-400 to-white text-gray-600 bg-size bg-top bg-no-repeat`}
            >
                <ReduxProviders>{children}</ReduxProviders>
            </body>
        </html>
    );
}
